<?php

namespace Database\Seeders;

use App\Models\News;
use App\Models\NewsCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class NewsSeeder extends Seeder
{
    public function run(): void
    {
        $categories = NewsCategory::all()->keyBy('slug');

        $news = [
            ['title' => 'Musyawarah Desa Pembahasan APBDes 2025', 'category' => 'pengumuman', 'content' => 'Pemerintah Desa Kleyang mengundang seluruh warga untuk hadir dalam Musyawarah Desa yang akan membahas Anggaran Pendapatan dan Belanja Desa (APBDes) tahun 2025. Kegiatan ini akan dilaksanakan pada hari Sabtu, 15 Januari 2025 bertempat di Balai Desa Kleyang.\n\nMusyawarah ini merupakan wujud transparansi dan akuntabilitas pemerintah desa kepada masyarakat. Seluruh rencana anggaran akan dipaparkan secara terbuka dan masyarakat diharapkan memberikan masukan dan saran yang konstruktif.\n\nHadir dalam musyawarah ini Kepala Desa, seluruh perangkat desa, BPD, tokoh masyarakat, dan perwakilan RT/RW se-Desa Kleyang.'],
            ['title' => 'Program Bedah Rumah Untuk Warga Kurang Mampu', 'category' => 'kegiatan', 'content' => 'Desa Kleyang kembali melaksanakan program Bedah Rumah bagi warga kurang mampu yang membutuhkan perbaikan hunian. Program ini merupakan salah satu bentuk kepedulian pemerintah desa terhadap warganya yang membutuhkan bantuan.\n\nTahun ini, sebanyak 5 unit rumah akan mendapatkan bantuan perbaikan yang meliputi perbaikan atap, dinding, dan lantai. Dana berasal dari Anggaran Dana Desa (ADD) dan bantuan dari Pemerintah Kabupaten Wonosobo.\n\nProses seleksi penerima manfaat dilakukan secara transparan berdasarkan kriteria yang telah ditetapkan. Warga yang memenuhi kriteria diharapkan mendaftarkan diri ke kantor desa.'],
            ['title' => 'Pembangunan Jalan Paving Dusun Krajan Dimulai', 'category' => 'pembangunan', 'content' => 'Proyek pembangunan jalan paving di Dusun Krajan resmi dimulai pada bulan ini. Proyek ini merupakan salah satu program prioritas pembangunan infrastruktur Desa Kleyang yang telah lama dinantikan warga setempat.\n\nPanjang jalan yang akan dibangun mencapai 350 meter dengan lebar 3 meter. Anggaran yang dialokasikan sebesar Rp 150 juta bersumber dari Dana Desa tahun 2024.\n\nKepala Desa Bambang Sutrisno menyatakan bahwa pembangunan jalan ini diharapkan dapat memperlancar akses warga ke pusat desa dan meningkatkan konektivitas antar dusun.'],
            ['title' => 'Sosialisasi Program Kartu Indonesia Sehat (KIS)', 'category' => 'sosialisasi', 'content' => 'Pemerintah Desa Kleyang bekerja sama dengan Puskesmas Mojotengah mengadakan sosialisasi Program Kartu Indonesia Sehat (KIS) bagi warga yang belum memiliki jaminan kesehatan.\n\nKegiatan sosialisasi dilaksanakan di Balai Desa Kleyang dan dihadiri oleh ratusan warga dari berbagai dusun. Narasumber dari Dinas Kesehatan Kabupaten Wonosobo menjelaskan cara pendaftaran, manfaat, dan prosedur penggunaan KIS.\n\nBagi warga yang belum memiliki KIS dan memenuhi kriteria sebagai warga tidak mampu, dapat mendaftarkan diri ke kantor desa untuk diproses lebih lanjut.'],
            ['title' => 'Festival Budaya Desa Kleyang 2024', 'category' => 'kegiatan', 'content' => 'Desa Kleyang menggelar Festival Budaya Desa yang meriah sebagai bentuk pelestarian tradisi dan budaya lokal. Festival ini menampilkan berbagai pertunjukan seni tradisional seperti wayang kulit, jathilan, dan tari-tarian daerah.\n\nKegiatan yang berlangsung selama dua hari ini juga dimeriahkan dengan pameran produk UMKM lokal, lomba memasak masakan tradisional, dan berbagai kegiatan menarik lainnya. Ratusan warga dari berbagai desa turut hadir menyaksikan festival ini.\n\nBapak Kepala Desa menyatakan bahwa festival ini merupakan upaya untuk memperkenalkan kekayaan budaya Desa Kleyang kepada masyarakat luas sekaligus sebagai ajang promosi wisata dan produk lokal.'],
            ['title' => 'KKN Mahasiswa Universitas Wonosobo di Desa Kleyang', 'category' => 'kegiatan', 'content' => 'Sebanyak 25 mahasiswa dari Universitas Wonosobo melaksanakan Kuliah Kerja Nyata (KKN) di Desa Kleyang selama 45 hari. Para mahasiswa ini akan membantu berbagai program pemberdayaan masyarakat dan pembangunan desa.\n\nProgram KKN yang akan dilaksanakan meliputi: pembuatan website profil desa, pendataan UMKM, pelatihan keterampilan warga, kegiatan mengajar di sekolah, dan program kesehatan masyarakat.\n\nKepala Desa menyambut hangat kehadiran mahasiswa KKN dan berharap program yang dilaksanakan dapat memberikan manfaat nyata bagi masyarakat Desa Kleyang.'],
            ['title' => 'Pelatihan UMKM Digital untuk Pelaku Usaha Desa', 'category' => 'sosialisasi', 'content' => 'Dinas Koperasi dan UMKM Kabupaten Wonosobo bersama Pemerintah Desa Kleyang mengadakan pelatihan digital marketing bagi pelaku UMKM di Desa Kleyang. Pelatihan ini bertujuan untuk meningkatkan kemampuan pemasaran produk lokal melalui platform digital.\n\nMateri yang disampaikan meliputi cara membuat toko online di marketplace, teknik fotografi produk, dan strategi pemasaran di media sosial. Para peserta sangat antusias mengikuti pelatihan ini.\n\nDiharapkan setelah pelatihan ini, produk UMKM Desa Kleyang dapat menjangkau pasar yang lebih luas dan meningkatkan pendapatan para pelaku usaha.'],
            ['title' => 'Pos Kamling Kembali Diaktifkan di Seluruh RT', 'category' => 'pengumuman', 'content' => 'Pemerintah Desa Kleyang bersama Babinsa dan Babinkamtibmas mengaktifkan kembali kegiatan Pos Kamling (Pos Keamanan Lingkungan) di seluruh RT se-Desa Kleyang. Langkah ini diambil untuk meningkatkan keamanan dan ketertiban masyarakat.\n\nJadwal ronda malam akan ditetapkan oleh masing-masing ketua RT dan diharapkan seluruh warga laki-laki yang telah berusia 17 tahun turut berpartisipasi. Kegiatan ini merupakan perwujudan sistem keamanan swakarsa berbasis masyarakat.\n\nKepala Desa menegaskan bahwa keamanan adalah tanggung jawab bersama dan mengajak seluruh warga untuk aktif menjaga keamanan lingkungan tempat tinggal masing-masing.'],
            ['title' => 'Posyandu Balita Rutin Dilaksanakan Tiap Bulan', 'category' => 'kegiatan', 'content' => 'Kegiatan Pos Pelayanan Terpadu (Posyandu) untuk balita dan ibu hamil rutin dilaksanakan setiap bulan di Desa Kleyang. Posyandu ini merupakan layanan kesehatan dasar yang sangat penting bagi masyarakat.\n\nLayanan yang diberikan meliputi penimbangan berat badan balita, pemberian imunisasi, pemantauan tumbuh kembang anak, dan konsultasi gizi. Para kader Posyandu yang terlatih siap melayani warga dengan sepenuh hati.\n\nBagi ibu-ibu yang memiliki anak balita dan ibu hamil diharapkan rutin mengunjungi Posyandu untuk memantau kesehatan dan tumbuh kembang anak.'],
            ['title' => 'Program Penyuluhan Pertanian Organik', 'category' => 'sosialisasi', 'content' => 'Dinas Pertanian Kabupaten Wonosobo mengadakan penyuluhan pertanian organik di Desa Kleyang. Program ini bertujuan untuk mendorong petani beralih ke metode pertanian organik yang lebih ramah lingkungan dan bernilai jual tinggi.\n\nNarasumber yang hadir merupakan ahli pertanian organik berpengalaman yang memberikan materi tentang pembuatan pupuk kompos, pestisida nabati, dan teknik budidaya organik.\n\nBeberapa petani menyambut antusias program ini dan berencana untuk mencoba menerapkan pertanian organik di lahan mereka. Pemerintah desa berkomitmen untuk terus mendukung pengembangan pertanian organik di Desa Kleyang.'],
            ['title' => 'Rehabilitasi Saluran Irigasi Pertanian Desa', 'category' => 'pembangunan', 'content' => 'Proyek rehabilitasi saluran irigasi pertanian Desa Kleyang sepanjang 500 meter telah selesai dilaksanakan. Proyek ini merupakan bagian dari program ketahanan pangan desa yang bertujuan untuk memastikan ketersediaan air bagi lahan pertanian.\n\nSaluran irigasi yang sebelumnya telah rusak kini telah diperbaiki dengan menggunakan bahan berkualitas. Petani yang lahannya dialiri oleh saluran irigasi ini sangat bersyukur karena produksi pertanian diharapkan meningkat.\n\nAnggaran rehabilitasi sebesar Rp 80 juta bersumber dari Dana Desa tahun 2024. Proses pengerjaan melibatkan tenaga kerja lokal dari masyarakat Desa Kleyang.'],
            ['title' => 'Pemberdayaan Kelompok Wanita Tani (KWT)', 'category' => 'kegiatan', 'content' => 'Kelompok Wanita Tani (KWT) Desa Kleyang semakin aktif dalam berbagai kegiatan produktif. Kelompok ini beranggotakan 30 ibu-ibu yang secara rutin mengikuti berbagai pelatihan dan kegiatan pengembangan diri.\n\nBeberapa program yang sedang berjalan antara lain budidaya sayuran organik di pekarangan rumah, pengolahan hasil pertanian menjadi produk bernilai tambah, dan pemasaran produk melalui media sosial.\n\nHasil dari kegiatan KWT ini tidak hanya memberikan tambahan penghasilan bagi keluarga tetapi juga meningkatkan ketahanan pangan keluarga. Program ini mendapat dukungan penuh dari pemerintah desa.'],
            ['title' => 'Peringatan Hari Kemerdekaan ke-79 di Desa Kleyang', 'category' => 'kegiatan', 'content' => 'Desa Kleyang merayakan Hari Kemerdekaan Republik Indonesia ke-79 dengan penuh semangat dan kegembiraan. Berbagai kegiatan telah dipersiapkan oleh panitia yang dibentuk dari unsur pemuda, perangkat desa, dan tokoh masyarakat.\n\nRangkaian kegiatan meliputi upacara bendera di lapangan desa, berbagai perlombaan tradisional untuk segala usia, pentas seni, dan malam tirakatan. Seluruh warga tampak antusias mengikuti berbagai kegiatan yang telah disiapkan.\n\nMomen peringatan kemerdekaan ini juga dimanfaatkan untuk mempererat tali silaturahmi antar warga dan membangkitkan semangat nasionalisme di kalangan generasi muda.'],
            ['title' => 'Pembukaan BUMDes Kleyang Mandiri', 'category' => 'pengumuman', 'content' => 'Desa Kleyang resmi meluncurkan Badan Usaha Milik Desa (BUMDes) dengan nama BUMDes Kleyang Mandiri. BUMDes ini diharapkan menjadi motor penggerak ekonomi desa dan meningkatkan pendapatan asli desa.\n\nUnit usaha yang akan dikelola BUMDes meliputi simpan pinjam, pengelolaan pasar desa, penyewaan peralatan pertanian, dan pengembangan wisata desa. Pengelolaan BUMDes akan dilakukan secara profesional dan transparan.\n\nMasyarakat diharapkan dapat berpartisipasi aktif dalam mendukung keberhasilan BUMDes melalui berbagai bentuk kerjasama yang saling menguntungkan.'],
            ['title' => 'Bantuan Sosial PKH Cair Untuk Warga Kleyang', 'category' => 'pengumuman', 'content' => 'Penyaluran bantuan sosial Program Keluarga Harapan (PKH) untuk warga Desa Kleyang telah dilaksanakan. Sebanyak 87 Keluarga Penerima Manfaat (KPM) mendapatkan bantuan yang disalurkan melalui rekening masing-masing.\n\nPenyaluran bantuan dilakukan secara non-tunai untuk memastikan tepat sasaran dan mengurangi risiko penyalahgunaan. Warga dapat mengambil bantuan di kantor pos atau ATM terdekat menggunakan Kartu Keluarga Sejahtera (KKS).\n\nPemerintah desa mengimbau kepada KPM untuk menggunakan bantuan ini sebaik-baiknya untuk memenuhi kebutuhan dasar keluarga terutama pendidikan dan kesehatan anak.'],
        ];

        foreach ($news as $item) {
            $catSlug = $item['category'];
            $category = $categories[$catSlug] ?? $categories->first();

            News::create([
                'news_category_id' => $category->id,
                'title'            => $item['title'],
                'slug'             => \Illuminate\Support\Str::slug($item['title']),
                'thumbnail'        => null,
                'excerpt'          => substr($item['content'], 0, 200) . '...',
                'content'          => $item['content'],
                'author'           => 'Admin Desa Kleyang',
                'is_published'     => true,
                'published_at'     => now()->subDays(rand(1, 180)),
                'views'            => rand(20, 500),
            ]);
        }
    }
}
